# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates',      'templates'),
        ('static',         'static'),
        ('version.txt',    '.'),
    ],
    hiddenimports=[
        'flask',
        'flask.templating',
        'jinja2',
        'werkzeug',
        'werkzeug.security',
        'sqlite3',
        'requests',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.backends',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'pystray',
        'pystray._win32',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'threading',
        'webbrowser',
        'modules.security',
        'modules.auth',
        'modules.users',
        'modules.bulletins',
        'modules.avis',
        'modules.system',
        'modules.config',
        'modules.contribuables',
        'modules.tnb',
        'modules.tdb',
        'modules.stationnement',
        'modules.fourriere',
        'modules.occupation',
        'modules.location',
        'modules.souks',
        'modules.regie',
        'modules.emission',
        'modules.registre',
        'modules.licensing',
        'modules.telemetry',
        'modules.updater',
        'modules.helpers',
        'openpyxl',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pandas',
        'numpy',
        'scipy',
        'matplotlib',
        'pyarrow',
        'llvmlite',
        'numba',
        'torch',
        'torchvision',
        'cv2',
        'sympy',
        'tensorflow',
        'transformers',
        'tokenizers',
        'huggingface_hub',
        'yt_dlp',
        'websockets',
        'pydantic',
        'shapely',
        'PyQt5',
        'PyQt6',
        'PySide6',
        'unittest',
        'pytest',
        'doctest',
        'IPython',
        'jupyter',
        'lxml',
        'psycopg2',
        'mysql',
    ],
    noarchive=False,
    optimize=2,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='JIBAYAT',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,                   # Masquer la console CMD
    disable_windowed_traceback=True, # Anti-reverse engineering: masquer les tracebacks
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='JIBAYAT',
)
